[base]
crs = 'EPSG:4326'
scale = 1000
reducer = 'median'
munis_1 = 'projects/ee-dengue-proof-of-concept/assets/munis_simple_1'
munis_2 = 'projects/ee-dengue-proof-of-concept/assets/munis_simple_2'
start_date = '2001-01-01'
end_date = '2022-01-01'
agg_unit = 'months'
agg_chunks = 6
save_dir = './data/gee_exports'
max_workers = 6

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'total_precipitation_min'

[[datasets]]
collection = 'MODIS/MOD09GA_006_EVI'
parameter = 'EVI'

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'temperature_2m'

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'total_precipitation_sum'

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'surface_runoff_min'

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'total_evaporation_sum'

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'runoff_sum'

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'evaporation_from_open_water_surfaces_excluding_oceans_min'

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'volumetric_soil_water_layer_1'

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'soil_temperature_level_1'

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'dewpoint_temperature_2m'

