[base]
crs = 'EPSG:4326'
scale = 1000
reducer = 'median'
munis_1 = 'projects/ee-dengue-proof-of-concept/assets/munis_simple_1'
munis_2 = 'projects/ee-dengue-proof-of-concept/assets/munis_simple_2'
start_date = '2001-01-01'
end_date = '2002-01-01'
agg_unit = 'months'
agg_chunks = 6
save_dir = './data/gee_exports'
max_workers = 6

[[datasets]]
collection = 'ECMWF/ERA5_LAND/DAILY_AGGR'
parameter = 'total_precipitation_min'

[[datasets]]
collection = 'MODIS/MOD09GA_006_EVI'
parameter = 'EVI'

